apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: server-go
  labels:
    app: server-go
spec:
  selector:
    matchLabels:
      app: server-go
  replicas: 3
  template:
    metadata:
     labels:
      app: server-go
    spec:
      containers:
      - name: server-go
        image: jbbatista/hello-go:latest