apiVersion: v1
kind: Service
metadata:
  name: go-server-service
spec:
  selector:
    app: server-go
  type: LoadBalancer
  ports:
    - name: go-server-service
      port: 8081
      targetPort: 8080
      protocol: TCP